all:
  children:
    app:
      hosts:
        app-01:
          ansible_host: <IP_VM_APP>
    loadbalancer:
      hosts:
        lb-01:
          ansible_host: <IP_VM_LB>
    monitoring:
      hosts:
        monitor-01:
          ansible_host: <IP_VM_MONITORING>
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_oracle