---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Deploy Nginx reverse proxy config
  ansible.builtin.template:
    src: nginx-app.conf.j2
    dest: /etc/nginx/sites-available/app
    mode: '0644'

- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    state: link
  notify: Restart nginx

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Enable and start Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
