---
- name: Apply common role to all hosts
  hosts: all
  become: true
  roles:
    - common

- name: Apply app role
  hosts: _app
  become: true
  roles:
    - app

- name: Apply loadbalancer role
  hosts: _loadbalancer
  become: true
  roles:
    - loadbalancer

- name: Apply monitoring role
  hosts: _monitoring
  become: true
  roles:
    - monitoring
